GET https://api.dawaafinder.com/blogapi/posts/

### Post the post
POST https://api.dawaafinder.com/blogapi/posts/
content-type: application/json

{
  "categoryId": "65d64cb4ec5719c7c481ed11",
  "image": "im3333333",
  "title": "New Title",
  "content": "lorem ipsum hheueueu",
  "creatorId": "65d64cb4ec5719c7c481ed11",
  "tagNames": [
    "Skin","Thhhsw"
  ]
}

### Get health organizations
GET https://api.dawaafinder.com/userapi/health-organizations/

GET https://api.dawaafinder.com/productapi/product-categories/

### Post to Product
POST https://api.dawaafinder.com/userapi/health-organizations/
content-type: application/json

{
  "name":"New Pharmma bet",
  "type":"Pharmacy"
}

