GET https://api.dawaafinder.com/blogapi/posts/

### Post the post
POST https://api.dawaafinder.com/blogapi/posts/
content-type: application/json

{
  "categoryId": "65d64cb4ec5719c7c481ed11",
  "image": "im3333333",
  "title": "New Title",
  "content": "lorem ipsum hheueueu",
  "creatorId": "65d64cb4ec5719c7c481ed11",
  "tagNames": [
    "Skin","Thhhsw"
  ]
}

### Get health organizations
GET https://api.dawaafinder.com/userapi/health-organizations/65dfb79102d42e990b3bef00

GET https://api.dawaafinder.com/productapi/product-categories/

### Post to Product
POST https://api.dawaafinder.com/userapi/health-organizations/
content-type: application/json

{
  "name":"New Pharmma bet",
  "type":"Pharmacy"
}
### Ads service
GET  https://api.dawaafinder.com/adsapi/ads
###
GET https://api.dawaafinder.com/adsapi/organizations
### Adding organization to the db
POST https://api.dawaafinder.com/adsapi/organizations
content-type: application/json

{
  "orgName":"Dr.Bonsa Clinic",
  "email":"bonsa@gmail.com",
  "phoneNumber":"09938382",
  "createdBy": "Abel"
}

###
POST  https://api.dawaafinder.com/userapi/system-admins/login/
Content-Type: application/json

{
  "username":"admin1",
   "password":"cc3377ch"
}

###
POST https://api.dawaafinder.com/userapi/system-admins/
Content-Type: application/json

{
  "username":"admin1"
 "password":"",

}
###
GET https://api.dawaafinder.com/userapi/health-orgs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzNjNTYxYjFiNGIyYTAwYTI2ZDdjOCIsInJvbGUiOiJzeXN0ZW1BZG1pbiIsImlhdCI6MTcyNDE0NDk4MywiZXhwIjoxNzMxOTIwOTgzfQ.Y8ZfDDaJrvSeL3B5vXD5I3aKqfDoAvys9sZbmLLCOGM

###
GET  https://api.dawaafinder.com/formularyapi/medicine-formularies/categories