GET https://api.dawaafinder.com/blogapi/posts/

### Post the post
POST https://api.dawaafinder.com/blogapi/posts/
content-type: application/json

{
  "categoryId": "65d64cb4ec5719c7c481ed11",
  "image": "im3333333",
  "title": "New Title",
  "content": "lorem ipsum hheueueu",
  "creatorId": "65d64cb4ec5719c7c481ed11",
  "tagNames": [
    "Skin","Thhhsw"
  ]
}

### Get health organizations
GET https://api.dawaafinder.com/userapi/health-organizations/65dfb79102d42e990b3bef00

GET https://api.dawaafinder.com/productapi/product-categories/

### Post to Product
POST https://api.dawaafinder.com/userapi/health-organizations/
content-type: application/json

{
  "name":"New Pharmma bet",
  "type":"Pharmacy"
}
### Ads service
GET  https://api.dawaafinder.com/adsapi/ads
###
GET https://api.dawaafinder.com/adsapi/organizations
### Adding organization to the db
POST https://api.dawaafinder.com/adsapi/organizations
content-type: application/json

{
  "orgName":"Dr.Bonsa Clinic",
  "email":"bonsa@gmail.com",
  "phoneNumber":"09938382",
  "createdBy": "Abel"
}

###
POST  https://api.dawaafinder.com/userapi/system-admins/login/
Content-Type: application/json

{
  "username":"abelk",
   "password":"12345678"
}

###
POST https://api.dawaafinder.com/userapi/system-admins/
Content-Type: application/json

{
 "firstName":"Abel",
 "lastName":"Kinfu",
 "username":"abelk",
 "role":"admin",
 "password":"12345678",
 "confirmPassword":"12345678",
 "phoneNumber":"12345678",
 "email":"abel@gmail.com"
}
###
GET https://api.dawaafinder.com/productapi/products
